"""empty message

Revision ID: 0fc9cf723185
Revises: ecad953f7a8f
Create Date: 2018-12-24 10:45:31.725000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc9cf723185'
down_revision = 'ecad953f7a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jumbotron_img', sa.Column('can_seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jumbotron_img', 'can_seen')
    # ### end Alembic commands ###
