"""empty message

Revision ID: 203c06527cda
Revises: 4aae50ec5f26
Create Date: 2018-12-25 11:53:42.350000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '203c06527cda'
down_revision = '4aae50ec5f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_index('password', table_name='user')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('password', 'user', ['password'], unique=True)
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
