"""empty message

Revision ID: 660a1d134442
Revises: bef6891f3d3e
Create Date: 2018-12-24 15:42:32.958000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660a1d134442'
down_revision = 'bef6891f3d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_log_id'), 'chat_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_log_id'), table_name='chat_log')
    op.drop_table('chat_log')
    # ### end Alembic commands ###
