"""empty message

Revision ID: 70427ab5b700
Revises: 99529b25cc57
Create Date: 2018-12-21 17:05:45.592000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70427ab5b700'
down_revision = '99529b25cc57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jumbotron_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jumbotron_img_id'), 'jumbotron_img', ['id'], unique=False)
    op.create_table('star_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_star_user_id'), 'star_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_star_user_id'), table_name='star_user')
    op.drop_table('star_user')
    op.drop_index(op.f('ix_jumbotron_img_id'), table_name='jumbotron_img')
    op.drop_table('jumbotron_img')
    # ### end Alembic commands ###
