"""empty message

Revision ID: 829c2a47dd7f
Revises: 4e356ce25564
Create Date: 2018-12-19 16:11:16.114000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829c2a47dd7f'
down_revision = '4e356ce25564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('self_top_comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['self_top_comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'self_top_comment_id')
    # ### end Alembic commands ###
