"""empty message

Revision ID: 99529b25cc57
Revises: a4a949f6ce08
Create Date: 2018-12-21 09:51:14.662000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99529b25cc57'
down_revision = 'a4a949f6ce08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('louceng', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'louceng')
    # ### end Alembic commands ###
