"""empty message

Revision ID: bef6891f3d3e
Revises: 0fc9cf723185
Create Date: 2018-12-24 11:55:14.864000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef6891f3d3e'
down_revision = '0fc9cf723185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jumbotron_img', sa.Column('description', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jumbotron_img', 'description')
    # ### end Alembic commands ###
